### ISSUE TITLE
Centering-logo

### ISSUE THREAD

**Issue by Hadeelalhaj** [Hadeelalhaj/Hadeelalhaj.github.io#1]
1- I have an issue by centering my logo in the middle of the page.
2- mouse cursor: when i click nothing happens while it should add a solid border .{ i mad toggled comments for the code}

**Comment by gorazd** [comment]
1. It's because you are centering the top left corner of your logo in the middle of the page. If you know the size of your logo-container (let's say 200px x 100px), you can use the calc function:
```css
.logo-container {
  text-align: center;
  position: absolute;
  top: calc(50% - 100px);
  left: calc(50% - 50px);
}
```
